import 'dart:convert';
import 'dart:typed_data';

/// Standalone helper: `dart run tool/encode_link_values.dart`.
///
/// Emits the ready-to-paste byte-array constants for
/// `lib/nova_link/config/link_config.dart`. Every entry ships as a
/// pseudo-random keystream XOR of the plaintext, so no host / secret ever
/// appears as a plain UTF-8 substring inside the compiled binary. The
/// tool prints a VERIFY block: paste the block into the config file, run
/// the app once, and confirm the decoded values match the plaintext.
///
/// If the cipher parameters below are rotated, re-run this tool and paste
/// the fresh output. Keep this file byte-identical to the runtime cipher
/// in `lib/nova_link/core/veil_cipher.dart`.

const int _veilSeed = 0x9C7B4E31;
const int _veilMul = 214013;
const int _veilAdd = 2531011;
const int _veilMask = 0xFFFFFFFF;
const int _veilShift = 8;

Uint8List _keystream(List<int> data) {
  final out = Uint8List(data.length);
  var state = _veilSeed;
  for (var i = 0; i < data.length; i++) {
    state = (state * _veilMul + _veilAdd) & _veilMask;
    out[i] = data[i] ^ ((state >> _veilShift) & 0xff);
  }
  return out;
}

List<int> _encode(String plain) => _keystream(utf8.encode(plain));

String _decode(List<int> encoded) => utf8.decode(_keystream(encoded));

String _asDart(List<int> bytes) {
  final buf = StringBuffer('<int>[');
  for (var i = 0; i < bytes.length; i++) {
    if (i > 0) buf.write(', ');
    buf.write('0x${bytes[i].toRadixString(16).padLeft(2, '0').toUpperCase()}');
  }
  buf.write(']');
  return buf.toString();
}

void main() {
  final entries = <String, String>{
    // Backend + partner endpoints. Runtime values are preserved so the
    // server contract, Firebase mapping and AppsFlyer wiring keep working.
    'relayEndpoint':      'https://boltofaether.com/config.php',
    'appsflyerDevKey':    'VdZ3pCJaQNjAuHsUK8SkqW',
    'firebaseProjectId':  '676540429694',
    'gcdBaseUrl':         'https://gcdsdk.appsflyer.com/install_data/v5.0/',
    'oneLinkTemplate':    'https://boltaether.onelink.me/32lj/5p4u59ko',

    // Browser UA scaffolding. Assembled at runtime piece-by-piece so the
    // canonical Safari substrings are not present in the compiled image.
    'uaProduct':          'Mozilla/5.0',
    'uaPlatformPrefix':   '(iPhone; CPU iPhone OS',
    'uaPlatformSuffix':   'like Mac OS X)',
    'uaEngine':           'AppleWebKit/605.1.15 (KHTML, like Gecko)',
    'uaMobileToken':      'Mobile/15E148',
    'uaVersionTag':       'Version/',
    'uaSafariTag':        'Safari/',
    'uaSafariTail':       '604.1',
    'uaSafariMajorMinor': '18.2',
    'uaAppIdToken':       'appid/',
    'uaAppNameToken':     'appname/',
    'uaBundleValue':      '6797957269',
    'uaAppNameValue':     'BoltOfAether',

    // Real bundle id — must match Xcode / Gradle so partner push routing
    // continues to address this exact application on the server side.
    'bundleId':           'com.boltaether.boltaethergame',

    // Local persistence namespace + cold-start URL key. Freshly minted
    // per project so no legacy key clashes with an earlier install.
    'ledgerPrefix':       'nova.link.',
    'coldLinkKey':        'nova_launch_link',
  };

  print('// ============================================================');
  print('// Generated by tool/encode_link_values.dart');
  print('// Paste into lib/nova_link/config/link_config.dart');
  print('// ============================================================');
  print('');

  final decoded = <String, String>{};
  for (final entry in entries.entries) {
    final bytes = _encode(entry.value);
    print('static const List<int> _${entry.key} = ${_asDart(bytes)};');
    decoded[entry.key] = _decode(bytes);
  }

  print('');
  print('// -------- VERIFY (round-trip) --------');
  var allOk = true;
  for (final entry in entries.entries) {
    final ok = decoded[entry.key] == entry.value;
    allOk = allOk && ok;
    print('// ${entry.key.padRight(22)}  ${ok ? 'OK' : 'MISMATCH'}   ${entry.value}');
  }
  print('// -------- ${allOk ? 'ALL OK' : 'FAILURE'} --------');
  if (!allOk) {
    throw StateError('Round-trip mismatch — do not ship these arrays.');
  }
}
