import 'dart:convert';
import 'dart:typed_data';

/// Standalone: `dart run tool/encode_relay_values.dart`
///
/// Encodes every secret/URL string into `List<int>` byte arrays that live in
/// `lib/aether_gate/config/relay_config.dart`. The tool ships a `VERIFY`
/// block at the bottom of its output: paste both blocks into the config file
/// and the round-trip is proved byte-for-byte before commit.
///
/// If you rotate `_lcgSeed` in `bolt_cipher.dart`, re-run this tool and
/// paste the fresh arrays.

// Must stay byte-for-byte identical to `lib/aether_gate/core/bolt_cipher.dart`.
const int _lcgSeed = 0x5F3AC91D;
const int _lcgMul = 1664525;
const int _lcgAdd = 1013904223;
const int _word = 0xFFFFFFFF;

Uint8List _stream(List<int> data) {
  final out = Uint8List(data.length);
  var state = _lcgSeed;
  for (var i = 0; i < data.length; i++) {
    state = (state * _lcgMul + _lcgAdd) & _word;
    out[i] = data[i] ^ ((state >> 16) & 0xff);
  }
  return out;
}

List<int> _encode(String plain) => _stream(utf8.encode(plain));

String _decode(List<int> encoded) => utf8.decode(_stream(encoded));

String _asDart(List<int> bytes) {
  final buf = StringBuffer('<int>[');
  for (var i = 0; i < bytes.length; i++) {
    if (i > 0) buf.write(', ');
    buf.write('0x${bytes[i].toRadixString(16).padLeft(2, '0').toUpperCase()}');
  }
  buf.write(']');
  return buf.toString();
}

void main() {
  final entries = <String, String>{
    // --- gray-flow endpoints and identity ---
    'relayEndpoint':      'https://boltofaether.com/config.php',
    'appsflyerDevKey':    'VdZ3pCJaQNjAuHsUK8SkqW',
    'firebaseProjectId':  '676540429694',
    'gcdBaseUrl':         'https://gcdsdk.appsflyer.com/install_data/v5.0/',
    // Full OneLink URL kept as one blob for the deferred-deep-link warmup;
    // never rendered plain in the binary.
    'oneLinkTemplate':
        'https://boltaether.onelink.me/32lj/5p4u59ko',

    // --- User-Agent scaffolding (every substring the scanner would match) ---
    'uaProduct':          'Mozilla/5.0',
    'uaPlatformPrefix':   '(iPhone; CPU iPhone OS',
    'uaPlatformSuffix':   'like Mac OS X)',
    'uaEngine':           'AppleWebKit/605.1.15 (KHTML, like Gecko)',
    'uaMobileToken':      'Mobile/15E148',
    'uaVersionTag':       'Version/',
    'uaSafariTag':        'Safari/',
    'uaSafariTail':       '604.1',
    'uaSafariMajorMinor': '18.2',
    // Slot-game partner identity suffix (per gray_user_agent.mdc §2 the operator
    // chose "encoded suffix": every token below ships as a byte array; nothing
    // plaintext lands in the binary).
    'uaAppIdToken':       'appid/',
    'uaAppNameToken':     'appname/',
    // The `appid/` token is followed by the App Store numeric id prefixed
    // with `id` (matches `AetherRelayConfig.platformStoreId`). Result at
    // runtime: `appid/id6797957269`. Kept SEPARATE from `bundleId` below
    // because the backend keys campaign/push routing on the real iOS
    // bundle identifier — swapping the two breaks server-side push
    // targeting (symptom: 2nd notification never arrives).
    'uaBundleValue':      'id6797957269',
    'uaAppNameValue':     'BoltOfAether',

    // --- real iOS bundle identifier, used as the `bundle_id` field of the
    //     config POST body. MUST match `PRODUCT_BUNDLE_IDENTIFIER` in
    //     Xcode / `applicationId` in Gradle so the backend can address
    //     this exact app when scheduling pushes. ---
    'bundleId':           'com.boltaether.boltaethergame',

    // --- storage keys (per-project, per gray_part_mixing_review §1) ---
    'vaultPrefix':        'agate.relay.',
    'vaultLaunchKey':     'agate_launch_route',
  };

  print('// ============================================================');
  print('// Generated by tool/encode_relay_values.dart');
  print('// Paste into lib/aether_gate/config/relay_config.dart');
  print('// ============================================================');
  print('');

  final decoded = <String, String>{};
  for (final entry in entries.entries) {
    final bytes = _encode(entry.value);
    print('static const List<int> _${entry.key} = ${_asDart(bytes)};');
    decoded[entry.key] = _decode(bytes);
  }

  print('');
  print('// -------- VERIFY (round-trip) --------');
  var allOk = true;
  for (final entry in entries.entries) {
    final ok = decoded[entry.key] == entry.value;
    allOk = allOk && ok;
    print('// ${entry.key.padRight(22)}  ${ok ? 'OK' : 'MISMATCH'}   ${entry.value}');
  }
  print('// -------- ${allOk ? 'ALL OK' : 'FAILURE'} --------');
  if (!allOk) {
    throw StateError('Round-trip mismatch — do not ship these arrays.');
  }
}
