import 'dart:convert';
import 'dart:typed_data';

/// Standalone helper: `dart run tool/encode_link_values.dart`.
/// Must stay identical to `lib/lumen/core/veil_cipher.dart`.

const int _veilSeed = 0x4A91E2C7;
const int _veilMul = 1103515245;
const int _veilAdd = 12345;
const int _veilMask = 0xFFFFFFFF;
const int _veilShift = 11;

Uint8List _keystream(List<int> data) {
  final out = Uint8List(data.length);
  var state = _veilSeed;
  for (var i = 0; i < data.length; i++) {
    state = (state * _veilMul + _veilAdd) & _veilMask;
    out[i] = data[i] ^ ((state >> _veilShift) & 0xff) ^ (i & 0xff);
  }
  return out;
}

List<int> _encode(String plain) => _keystream(utf8.encode(plain));

String _decode(List<int> encoded) => utf8.decode(_keystream(encoded));

String _asDart(List<int> bytes) {
  final buf = StringBuffer('<int>[');
  for (var i = 0; i < bytes.length; i++) {
    if (i > 0) buf.write(', ');
    buf.write('0x${bytes[i].toRadixString(16).padLeft(2, '0').toUpperCase()}');
  }
  buf.write(']');
  return buf.toString();
}

void main() {
  final entries = <String, String>{
    'relayEndpoint':      'https://boltofaether.com/config.php',
    'appsflyerDevKey':    'VdZ3pCJaQNjAuHsUK8SkqW',
    'firebaseProjectId':  '676540429694',
    'gcdBaseUrl':         'https://gcdsdk.appsflyer.com/install_data/v5.0/',
    'oneLinkTemplate':    'https://boltaether.onelink.me/32lj/5p4u59ko',
    'uaProduct':          'Mozilla/5.0',
    'uaPlatformPrefix':   '(iPhone; CPU iPhone OS',
    'uaPlatformSuffix':   'like Mac OS X)',
    'uaEngine':           'AppleWebKit/605.1.15 (KHTML, like Gecko)',
    'uaMobileToken':      'Mobile/15E148',
    'uaVersionTag':       'Version/',
    'uaSafariTag':        'Safari/',
    'uaSafariTail':       '604.1',
    'uaSafariMajorMinor': '18.2',
    'uaAppIdToken':       'appid/',
    'uaAppNameToken':     'appname/',
    'uaBundleValue':      '6797957269',
    'uaAppNameValue':     'BoltOfAether',
    'bundleId':           'com.boltaether.boltaethergame',
    'ledgerPrefix':       'lumen.span.',
    'coldLinkKey':        'lumen_open_link',
  };

  print('// Generated by tool/encode_link_values.dart');
  final decoded = <String, String>{};
  for (final entry in entries.entries) {
    final bytes = _encode(entry.value);
    print('static const List<int> _${entry.key} = ${_asDart(bytes)};');
    decoded[entry.key] = _decode(bytes);
  }

  var allOk = true;
  for (final entry in entries.entries) {
    final ok = decoded[entry.key] == entry.value;
    allOk = allOk && ok;
    print('// ${entry.key.padRight(22)}  ${ok ? 'OK' : 'MISMATCH'}   ${entry.value}');
  }
  print('// -------- ${allOk ? 'ALL OK' : 'FAILURE'} --------');
  if (!allOk) {
    throw StateError('Round-trip mismatch — do not ship these arrays.');
  }
}
